#!/usr/bin/env bash

# Andy Sayler
# CSCI 1300 Package
# postinst Script

set -e

echo "Installing PIP packages"
pip install -r /usr/share/cu-cs-csci-1320/python/requirments.txt
pip3 install -r /usr/share/cu-cs-csci-1320/python/requirments.txt
