#!/bin/sh

# Andy Sayler
# cu-cs-csci4830-advrobo-rosrepo Package
# preinst Script
# Purpose: Adds ROS repo
# Created 01/2013

echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list
wget http://packages.ros.org/ros.key -O - | apt-key add -
