#!/bin/sh

# Andy Sayler
# cu-cs-csci4830-advrobo Package
# postinst Script
# Purpose: Setup ROS
# Created 01/2013

rosdep init
# What does 'update' do? The install instructions say it doesn't need to be run as root...
rosdep update
