#!/usr/bin/env bash

# Andy Sayler
# CSCI 5832 Package
# postinst Script

set -e

echo "Installing PIP packages"
pip install -r /usr/share/cu-cs-csci-5832/python/requirments.txt -U
pip3 install -r /usr/share/cu-cs-csci-5832/python/requirments.txt -U
