#!/usr/bin/env bash

# Andy Sayler
# CSCI 1310 Package
# postinst Script

set -e

echo "Installing PIP packages"
pip2 install -r /usr/share/cu-cs-csci-1310/python/requirments.txt -U
pip3 install -r /usr/share/cu-cs-csci-1310/python/requirments.txt -U
