#!/usr/bin/env bash

# Andy Sayler
# CS CS VM Package
# postinst Script

background="/usr/share/backgrounds/CU-CS-VM-Background.png"

# Set Desktop Background
gsettings set org.gnome.desktop.background picture-uri "file://${background}"

# TODO
# Automate /usr/share/polkit-1/actions/org.debian.apt.policy changes
# Change to: <allow_active>yes</allow_active>

exit 0