#!/usr/bin/env bash

keys=("/etc/apt/trusted.gpg.d/csel-andy.gpg" "/etc/apt/trusted.gpg.d/csel-matt.gpg")

for key in ${keys[@]}
do
    echo "Checking ${key}"
    if [ -f "${key}" ]
    then
	echo "${key} exists"
	dpkg -S "${key}" &> /dev/null
	if [ $? -ne 0 ]
	then
	    echo "${key} not controlled by package"
	    echo "Removing ${key}"
	    rm "${key}"
	else
	    echo "${key} controlled by package"
	    echo "Ignoring ${key}"
	fi
    else
	echo "${key} does not exist"
    fi
done
