#!/usr/bin/env bash

# Andy Sayler
# CSCI 3308 Package
# postinst Script
# Purpose: Installs Ruby Gems
# Created 10/2013

# install a bunch of gems
echo "Installing ruby gems to ${HOME}"
pushd ${HOME}
gem install bundler
gem install capybara # -v 1.1.1
gem install cucumber # -v 1.0.6
gem install execjs
gem install factory_girl
gem install flay
gem install flog
gem install haml # -v 3.1.3
#gem install heroku # -v 2.8.0
gem install nokogiri # -v 1.5.0
gem install rails_best_practices
gem install rails # -v 3.1.0
#gem install rcov # -v 0.9.10
gem install simplecov
gem install reek
gem install rspec-rails # -v 2.6.1
gem install ruby-debug19
gem install ruby-tmdb
gem install simplecov
gem install sqlite3 # -v 1.3.4
gem install taps
gem install therubyracer
gem install thinking-sphinx
gem install uglifier # -v 1.0.3
popd

# rails hack to add therubyracer to the default gemfile
#cd /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails
#sudo chmod 777 generators/
#cd generators/
#sudo chmod 777 app_base.rb
# this adds gem 'therubyracer' to the default gem file, by it after gem 'uglifier'
#sed '/gem '"'uglifier'"'/ a\            gem '"'therubyracer'"'' app_base.rb > app_base2.rb
#mv app_base2.rb app_base.rb
#sudo chmod 644 app_base.rb
#cd ..
#sudo chmod 755 generators
#cd ~/Documents

exit 0
