#!/usr/bin/env bash

# Andy Sayler
# CSCI 1300 Package
# postinst Script

# ToDo
# Setup Python 3 as Geany Default
# See http://terminalobsession.blogspot.com/2012/06/how-to-get-geany-to-use-python3-as-its.html

echo 0
